# This workflow will build a Java project with Maven and push docker image into registory

name: maven build and docker image push

on:
  push:
    branches: [ main ]

jobs:

  maven:
    name: maven build and docker image
    runs-on: ubuntu-18.04
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }}
          -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag $REPO:latest
      - name: Publish Docker image
        run: docker push $REPO
